version: '3.8'

services:
  rtos-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rtos_workspace
      - /dev:/dev
    environment:
      - NETBURNER_SDK=/opt/netburner/sdk
      - DEBUG_LEVEL=info
      - TERM=xterm-256color
    networks:
      - rtos_net
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    cap_add:
      - SYS_PTRACE
      - SYS_RAWIO
    security_opt:
      - seccomp:unconfined
    privileged: true
    tty: true
    stdin_open: true

networks:
  rtos_net:
    driver: bridge
